# hostname (and path) to the root, e.g. http://spf13.com/
baseURL =             "https://droids.work/"

# site title
title =               "droids.work"

# maximum number of items in the RSS feed
rssLimit =            15

# true: use pygments-css or false: color-codes directly
pygmentsUseClasses =  true


[params]
  subtitle =          "There is a 97.6 percent chance of failure."
  author =            "Vaughan Lapsley"
  email =             "vaughan.lapsley@gmail.com"
  description =       "Congratulations. You are being rescued. Please do not resist."
  keywords =          "system administration, amazon aws, devops, azure, minecraft, powershell, docker"
  # Social buttons
  [[params.socialbuttons]]
  faicon =            "github"
  url =               "https://github.com/vlapsley"
  [[params.socialbuttons]]
  faicon =            "twitter"
  twitterURL =        "https://twitter.com/vlapsley"
  [[params.socialbuttons]]
  faicon =            "linkedin"
  linkedinURL =       "https://linkedin.com/in/vlapsley"

  disqusShortname =   "vlapsley"

[taxonomies]
  tag =               "tags"
  category =          "categories"