baseurl = "https://droids.work/"
theme = "geo"
relativeURLs = false
languageCode = "en-us"
title = "droids.work"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true
	favicon = "favicon.ico"
	analytics = "code-here"
	profilepic = "img/avatar.png"

	header = "Congratulations. You are being rescued. Please do not resist."
	title = "Vaughan Lapsley"
	subtitle = "Droid"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/vlapsley"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/vlapsley"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com/in/vlapsley"

	[[params.navlinks]]
	name = "About Me"
	url = "about/"
	
	[[params.navlinks]]
	name = "Blog"
	url = "posts/"
	
	[[params.navlinks]]
	name = "Contact"
	url = "contact/"
