# hostname (and path) to the root, e.g. http://spf13.com/
baseURL =             "https://droids.work/"

# site title
title =               "droids.work"

# maximum number of items in the RSS feed
rssLimit =            15

# true: use pygments-css or false: color-codes directly
pygmentsUseClasses =  true

# Pagination
paginate =            10
paginatePath =        "page"

[author]
    name = "Vaughan Lapsley"

[params]
  subtitle =          "There is a 97.6 percent chance of failure."
  author =            "Vaughan Lapsley"
  email =             "vaughan.lapsley@gmail.com"
  description =       "Congratulations. You are being rescued. Please do not resist."
  keywords =          "system administration, amazon aws, devops, azure, minecraft, powershell, docker"
  disqusShortname =   "vlapsley"
  # Social buttons
  [[params.socialbuttons]]
  faicon =            "github"
  url =               "https://github.com/vlapsley"
  [[params.socialbuttons]]
  faicon =            "twitter"
  url =               "https://twitter.com/vlapsley"
  [[params.socialbuttons]]
  faicon =            "linkedin"
  url =               "https://linkedin.com/in/vlapsley"

[taxonomies]
  tag =               "tags"
  category =          "categories"

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 1

[[menu.main]]
  name = "About Me"
  url = "/page/about/"
  weight = 2